added vless alias

diff --git a/dotfiles/aliases b/dotfiles/aliases
--- a/dotfiles/aliases
+++ b/dotfiles/aliases
@@ -144,6 +144,38 @@ fi
 # }}}
 
 # FUNCTIONS {{{
+function vless() {
+    # /usr/share/vim/vim74/macros/less.sh
+    # Shell script to start Vim with less.vim.
+    # Read stdin if no arguments were given and stdin was redirected.
+    if test -t 1; then
+        if test $# = 0; then
+            if test -t 0; then
+                echo "Missing filename" 1>&2
+                exit
+            fi
+            vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' -
+        else
+            vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' "$@"
+        fi
+    else
+        # Output is not a terminal, cat arguments or stdin
+        if test $# = 0; then
+            if test -t 0; then
+                echo "Missing filename" 1>&2
+                exit
+            fi
+            cat
+        else
+            cat "$@"
+        fi
+    fi
+}
+
+function ccat() {
+    pygmentize -g "$@" | less
+}
+
 function mc() {
     cwd_file=/tmp/mc-$USER-$$-dir
     env mc -c --printwd=$cwd_file "$@"
